### ISSUE TITLE
404 found for stream-reactor-0.2-3.0.1

### ISSUE THREAD

**Issue by nathgopi45** [datamountaineer/stream-reactor#106]
I couldnt able to download the following stream connector version.
stream-reactor-0.2-3.0.1.
Im getting 404 for https://github.com/datamountaineer/stream-reactor/releases/tag/v0.2.3
this is the url it is given in datamountaineer docs for mongodb sink connector to install stream-reactor as in
http://docs.datamountaineer.com/en/stable/install.html#install

**Comment by andrewstevenson** [comment]
Yes. We, rather i broke the build. We'll publish it for you tonight.
________________________________

**Comment by nathgopi45** [comment]
Thanks a lot for the quick response, I can able to setup and testing for mongodb sink.
in that progress,
when i run the following command, 
      bin/cli.sh create mongo-sink < conf/mongodb-sink.properties
im getting the below error,
2017-01-05 10:42:49,032 ERROR [DistributedHerder] [o.a.k.c.r.WorkerConnector] [doStart:108] Error while starting connector mongo-sink
org.apache.kafka.connect.errors.ConnectException: Couldn't start Mongo sink due to configuration error: Missing required configuration "connect.mongo.connection" which has no default value.

And because of that my MongoSink connector is not initialized.Any idea where can i give the value for the property "connect.mongo.connection".

My mongodb sink properties has following contents:
name=mongo-sink-orders
connector.class=com.datamountaineer.streamreactor.connect.mongodb.sink.MongoSinkConnector
tasks.max=1
topics=orders-topic
connect.mongo.sink.kqcl=INSERT INTO orders SELECT * FROM orders-topic
connect.mongo.database=connect
connect.mongo.hosts=localhost:27017
connect.mongo.sink.batch.size=10

**Comment by stheppi** [comment]
@nathgopi45 ,
I need to fix the documentation and the sample configuration since they are not in line with the code

Connect.mongo.hosts needs to be replaced in your sink configuration with
connect.mongo.connection ="The mongodb connection in the format mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]."

**Comment by nathgopi45** [comment]
Sure .. Thats ok..
And thanks a lot for the quicker responses.
Please make sure we need to update the following property name too..
connect.mongo.sink.kcql instead of connect.mongo.sink.kqcl..
i think, its typo.
kcql from kqcl ..
i will get back if in case anything i would have found more

**Comment by nathgopi45** [comment]
Looking forward for the new updated document. I can able to successfully complete mongodb sink now..thanks a lot guys.. you guys make my new year kickoff like cake walk..
