### ISSUE TITLE
CassandraSink ConsistencyLevel

### ISSUE THREAD

**Issue by Mematematica** [datamountaineer/stream-reactor#108]
I see no way to set the consistency level to use. What's the default one used?
Is there a way to set the consistency level to local quorum?

Thank you in advance

**Comment by stheppi** [comment]
@Mematematica not at the moment. The default for 3.0 drivers is Local one. we will add a config option to allow setting it up.

**Comment by Mematematica** [comment]
@stheppi Thank you very much. I hope it is implemented soon. Cheers!

**Comment by stheppi** [comment]
@Mematematica 
 We have added the support for the consistency level. you can set the connect.cassandra.consistency.level property to overwrite the default. while we prepare our 0.2.4 release you can grab the latest code and build it locally.

**Comment by Mematematica** [comment]
awesome, thank you guys!
