### ISSUE TITLE
HBase sink: Schema{org.apache.kafka.connect.data.Timestamp:INT64} is not a recognized schema!

### ISSUE THREAD

**Issue by EverlastingSong** [datamountaineer/stream-reactor#112]
When I used HBaseSink to consume data into Hbase, the worker log said:
java.lang.RuntimeException: Schema{org.apache.kafka.connect.data.Timestamp:INT64} is not a recognized schema!: 
I'm using the avro convertor. The data consumed is produced by a jdbc source connector with avro convertor.
The schema of the column that causing the error is  
 {
      "name": "last_modified_date",
      "type": {
        "type": "long",
        "connect.version": 1,
        "connect.name": "org.apache.kafka.connect.data.Timestamp"
      }
 }
This schema is produced by the jdbc source connector

**Comment by stheppi** [comment]
@EverlastingSong 
Our next release will contain it but until then you can get the latest and build locally.

**Comment by Fatema** [comment]
This error still appears even with the newest release

**Comment by Antwnis** [comment]
The latest available release is dated 1st Sept. 

We are planning a new release in early December. 
On the meanwhile please build the JAR from `master`
