### ISSUE TITLE
Feature Request for Druid Source Connector

### ISSUE THREAD

**Issue by austindsouza** [datamountaineer/stream-reactor#117]
Hi,

I'm looking for the functionality of Druid Source Connector, which will get the data from Druid and stream it in kafka topic.

**Comment by andrewstevenson** [comment]
@austindsouza We can look at it. First we have other connectors to finish. We can change the priority but we normally only do this on commercial terms. Send me a direct mail if you want to discuss this.

**Comment by austindsouza** [comment]
@andrewstevenson I am new to Confluient,  If i wanted to write druid source connector using Apache Calcite's jdbc driver what is the approach or what all things do I need?

Can you guide me?

**Comment by andrewstevenson** [comment]
Not on our radar so closing for now
