### ISSUE TITLE
Redis Cache mode INSERT INTO suffix

### ISSUE THREAD

**Issue by LukeFieldsend** [datamountaineer/stream-reactor#119]
Hey I'm configuring a kafka connect Redis sink and I would like to suffix my keys with a string. 
i.e <key>:FOO

from the docs i see you can specify a prefix using  INSERT INTO

 INSERT INTO FX- SELECT price from yahoo-fx PK symbol

is the same possible for a suffix

INSERT INTO  SELECT * from kafkaTopic PK KeyColumn :FOO

i receive an error 
Invalid syntax.failed to parse at line 1 due to mismatched input 'SELECT' expecting {ID, TOPICNAME}

so it's expecting something after the INSERT INTO

cheers

Luke

EDIT:  If this isn't supported am I better preshaping the key with a suffix before it hits kafka

**Comment by Antwnis** [comment]
Suffixes are not currently supported.
Can you please give us an example use-case where that would make sense 

We could then discuss and see if / and how this capability can be supported

**Comment by LukeFieldsend** [comment]
Hey @Antwnis 

I'm caching a large number of json blobs representing device metadata and using kafka-connect to do a migration of this data from sql -> kafka -> redis. 

The current format i use is as the key for the blob is "(<guid>:device ->blob) and I also save a lookup index key value pair pointing at the device blobs key (<deviceSubKey>:subkey-device ->deviceSubKey value)

The only difference between what is supported now and my use case is that i use key suffixes. I use sql views to shape the data before it enters kafka. As a work around  I can add the guid with suffix as a column field and use that for PK

**Comment by stheppi** [comment]
Hey @LukeFieldsend,
 If my understanding is correct you want to have operation in KCQL something like SELECT f1+'_something' as col1 FROM source PK f2 + '_extra'.
 We intend to improve the support for KCQL but operations are not yet on the roadmap.

**Comment by LukeFieldsend** [comment]
Hey @stheppi 

Yes that's correct.

I've begun pre-shaping the data in the source sql view.to achieve this for now
