### ISSUE TITLE
Field "async" in InfluxDB

### ISSUE THREAD

**Issue by sebastianvoss** [datamountaineer/stream-reactor#120]
The connector includes a field `async` in the data records when writing to InfluxDB. 

This field is not part of the transferred payload (e.g. not defined in the Avro schema). What is the purpose of this field and is there any way to avoid it?

Payload:
    
     {"company": "DataMountaineer","address": "MontainTop","latitude": -49.817964,"longitude": -141.645812}

InfluxDB measurement:

    > select * from influxMeasure;
    name: influxMeasure
    -------------------
    time                address         async   company         latitude                longitude
    1478269679104000000 MontainTop      true    DataMountaineer -49.817962646484375     -141.64581298828125

**Comment by stheppi** [comment]
@sebastianvoss,
  in the upcoming release we fixed this. You can take the code from master and build it yourself. If you read the influxdb doc, you will find a Tag section where we added better suport for tags and the hardcoded 'async' is gone.
