### ISSUE TITLE
Debug cassandra sink - best practice

### ISSUE THREAD

**Issue by 0zeroth** [datamountaineer/stream-reactor#122]
Some documentation on how best to debug the Cassandra sink would be welcome.

My specific use case is I have an Avro topic stream that is working, I've configured a Cassandra sink with error policy "THROW", the connect REST API report the sink is "RUNNING", the connect logs look normal (all INFO level, committing offsets etc), but there is no data in Cassandra. At this point I'm at a loss on where to go next, and think some general documentation on debugging problems would be helpful.

Some information it would be useful to know (plus I'm sure the data mountaineer team have a lot more to add):
* Can we log the CQL insert statements?
* Can we confirm behaviour of bad commits - will it throw?
* Any insight on how to debug from the Cassandra side (ie if the connector is getting successful inserts, how to find the problem on Cassandra side)?

**Comment by stheppi** [comment]
@0zeroth,
  What version of cassandra do you use. 3.0.9 is required to fix a bug with json inserts

**Comment by andrewstevenson** [comment]
@0zeroth Please share your connector configs. We also have a slack channel that makes it easier to communicate?
