### ISSUE TITLE
Kafka-connect-redis WorkerSinkTask loggings

### ISSUE THREAD

**Issue by LukeFieldsend** [datamountaineer/stream-reactor#123]
Hello,

I'm writing a kafka=>redis sink task and receiving the following error
when i check the status of the running connector

org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:406) 

I am running kafka-connect within a docker container and it contains no further logs other then the connector was created. 

I checked the source code

[link](https://www.codatlas.com/github.com/apache/kafka/0.10.1/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java) noting at line 404 & 405 there should be error logs before the above error message was thrown. 404 containing the exception

For worker sink tasks is there an accessible log location to  view the real error

**Comment by Antwnis** [comment]
Hi @LukeFieldsend 

Can you please post some information including:
* Version of CP used
* Version of Stream-Reactor used
* Configuration / KCQL 

Will need to understand which Redis-mode (Sorted-Set | CACHE | Multiple Sorted-Sets) u are using - and how you are configuring the partiticular connector.

**Comment by LukeFieldsend** [comment]
hey @Antwnis 
cp-kafka-connect:3.1.1

I got my steam-reactor redis module from https://github.com/datamountaineer/stream-reactor/releases/download/v0.2.3/kafka-connect-redis-0.2.3-3.1.1-all.tar.gz

and my config is as follows

#Connector name=`redis-device-sink`
connect.redis.connection.host=redis-1
connect.redis.connection.port=6379
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=DeviceInfoMigrationKafkaConnect_DeviceImports
connect.redis.sink.kcql=SELECT pkstringfieldA, stringfieldb, timestampfielda, timestampfieldb, stringfieldc, stringfieldd, stringfielde, intfielda, arrayoftimestamps, arrayofrecords FROM kafka topic PK pkstringfieldA(with suffix pre appended)
#task ids: 0

**Comment by stheppi** [comment]
@LukeFieldsend 
Can you confirm the kafka avro console consumer you can consume the records on the topic?

(with suffix pre appended)=> is this your own support for KCQL?

you can start connect in local mode in your terminal pointing out to your kafka cluster and set the debug level on log4j?

**Comment by stheppi** [comment]
@LukeFieldsend 
you can always take the code locally and wrap in a try..catch block the RedisSinkTask#put and catch throwable to log it.

**Comment by LukeFieldsend** [comment]
Hey @stheppi 

I JdbcSourceConnector source connector to import these entities from an msql instance. I use a view to prepare this data, i added an extra column duplicating the column i wish to use for pk with a string suffix. so this is done before the records enter kafka. I will try the above suggestions and get back to you 

cheers
