### ISSUE TITLE
Kafka Connect Sink Cassandra contact points config

### ISSUE THREAD

**Issue by Pedroz14** [datamountaineer/stream-reactor#124]
I'm using Cassandra Sink Connector to extract data from a topic, my problem is that I'm trying to set three distinct contact points in my properties file like: 

`connect.cassandra.contact.points=cassNode1,cassNode2,cassNode3....`

but the Kafka Connect doesn't recognize this property.
What is the correct form to set this property?
Its implemented in the Connector?

Thanks so much!

**Comment by stheppi** [comment]
@Pedroz14,
  The property is defined for the connector and is mandatory? What is the error do you see? Which connector version do you use?

**Comment by Antwnis** [comment]
@stheppi Does the connector support multiple or a single contact point ?

https://github.com/datamountaineer/stream-reactor/blob/4eb8800bbde69813e70b05893598e581688da389/kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/CassandraConnection.scala#L41

    def getCluster(connectorConfig: AbstractConfig) : Cluster = {
    val contactPoints: String = connectorConfig.getString(CassandraConfigConstants.CONTACT_POINTS)
    val port = connectorConfig.getInt(CassandraConfigConstants.PORT)
    val builder: Builder = Cluster
      .builder()
      .addContactPoints(contactPoints)

**Comment by stheppi** [comment]
@Pedroz14 ,
 We have pushed the fix for this. Thank you for reporting this. Now it will take the value of 
 `connect.cassandra.contact.points`
 and split it by ','. 

We will do a release. But until then you can take and build the code to get the latest changes

**Comment by Antwnis** [comment]
Hi @Pedroz14 , you can also grab the latest release (v0.2.4) that includes the above fix from
https://github.com/datamountaineer/stream-reactor/releases/

**Comment by Pedroz14** [comment]
thanks so much for solve this issue!
