### ISSUE TITLE
connect.cassandra.sink.error.policy=Noop 

### ISSUE THREAD

**Issue by pawanjuly3** [datamountaineer/stream-reactor#131]
I am using JSON instead of AVRO. Everything works fine and all records goes to Cassandra and performance is also good using single task.

Default behavior thorw of "connect.cassandra.sink.error.policy" working but unable to change it to noop.

Using noop to retry to n times make no difference and it continues to throw errors instead of ignoring messages with wrong JSON structure until i clear topic and remove all messages.

Do we have this option enabled?

**Comment by Antwnis** [comment]
This will need to be looked at. On the meanwhile can you document into this ticket what is the performance you are experiencing and using which particular Cassandra version and connector version for future reference ?

**Comment by andrewstevenson** [comment]
@pawanjuly3 There's no DM error policy handling on the source. Are you using the Sink or Source?

> Default

 behavior thorw of "connect.cassandra.**source**.error.policy" working but unable to change it to noop.

**Comment by pawanjuly3** [comment]
I apologies. I will change original message but its sink policy
connect.cassandra.sink.error.policy=Noop

**Comment by pawanjuly3** [comment]
This is how my properties look

[‎01-‎03-‎2017 20:11] Sivasubbu Balaiah: 
connect.cassandra.key.space=mydb
connect.cassandra.contact.points=192.168.142.22
topics=mytopic
name=cassandra-sink-kafka-events
connect.cassandra.username=cassandra
tasks.max=1
connect.cassandra.port=9042
connect.cassandra.password=cassandra
connector.class=com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector
connect.cassandra.sink.kcql=INSERT INTO events_table SELECT event_id, event_date, event_value FROM mytopic;
connect.cassandra.sink.error.policy=Noop

**Comment by andrewstevenson** [comment]
Change to this connect.cassandra.error.policy=Noop

**Comment by pawanjuly3** [comment]
Still same behavior with below policy.

 connect.cassandra.error.policy=Noop

**Comment by pawanjuly3** [comment]
Hello Andrew this seems working with NOOP. Value is case sensitive, 
connect.cassandra.error.policy=NOOP

**Comment by pawanjuly3** [comment]
Andrew this worked with your suggestion.  Thanks for your help on this...
