### ISSUE TITLE
JMS Sink - using with WebSphere MQ

### ISSUE THREAD

**Issue by joewood** [datamountaineer/stream-reactor#132]
The JMS Sink code assumes that the JMS Factory class supports a single string in the constructor. 
The IBM MQ Series JMS Factory doesn't support this, instead it has a parameterless constructor and requires properties to be set after construction. It would be useful to support two stage construction through the use of an additional configuration properties defined dynamically E.g.

```ini
connector.class=com.datamountaineer.streamreactor.connect.jms.sink.JMSSinkConnector
tasks.max=1
topics=jms-topic
connect.jms.sink.connection.factory=com.ibm.mq.jms.MQConnectionFactory
connect.jms.sink.connection.factoryproperties.hostName=somehost
connect.jms.sink.connection.factoryproperties.queueManager=queueManagerName
connect.jms.sink.connection.factoryproperties.port=1234
connect.jms.sink.connection.factoryproperties.channelName=mychannel
```

**Comment by andrewstevenson** [comment]
@joewood Would you like to have a crack and submit a PR?

**Comment by joewood** [comment]
This works now with 2.5 using JNDI without my MQ specific modifications. So it can be closed.

**Comment by andrewstevenson** [comment]
Awesome. Thanks @joewood.
