### ISSUE TITLE
Cassandra Source should ignore specified columns in KCQL

### ISSUE THREAD

**Issue by CodeSmell** [datamountaineer/stream-reactor#134]
Having submitted a fix so that the SELECT columns are the only ones that are retrieved from Cassandra, there is still the need to include the time stamp column, which is required to handle the offsets. 

Is the best way to filter this out of the result set placed on the Topic using the KCQL IGNORE statement. 
If so I can work on adding that to the CassandraTableReader and CassandraUtils.

If there is another approach let me know.

**Comment by CodeSmell** [comment]
This PR is a possible fix
https://github.com/datamountaineer/stream-reactor/pull/136

**Comment by stheppi** [comment]
thanks.
