### ISSUE TITLE
Support for 0.10.2 Connectors and Transforms

### ISSUE THREAD

**Issue by joewood** [datamountaineer/stream-reactor#135]
Will the connectors in stream-reactor work with the 0.10.2 client SDK without rebuilding? And will they work with the simple transformations configured?

**Comment by stheppi** [comment]
We don't know of any breaking changes in 0.10.2 for connect. Although we haven't tested them with 0.10.2.
Transforms are applied in connect framework before the SinkRecord is handed over to the sink. so you can apply those transformations in the sink config
