### ISSUE TITLE
JMS Sink - Error when using schemaless JSON

### ISSUE THREAD

**Issue by joewood** [datamountaineer/stream-reactor#137]
For the JMS Sink Connector, when using schemaless JSON and a KCQL field list, the sink connector errors with the following exception:

```
[2017-03-07 14:06:21,655] ERROR Error: class java.util.HashMap is not valid. Expecting a Struct (com.datamountaineer.streamreactor.connect.jms.sink.writer.JMSWriter:101)
```
e.g. with a field list in KCQL:
```
connect.jms.sink.kcql=INSERT INTO QUEUE.NAME SELECT field1,field2,field3 FROM topic
```

The Sink works fine when using a wildcard select:
```
connect.jms.sink.kcql=INSERT INTO QUEUE.NAME SELECT * FROM topic
```

**Comment by andrewstevenson** [comment]
@joewood Can you confirm this is solved now? Its only works when storing json text messages into the jms target.

**Comment by andrewstevenson** [comment]
@Norwood closing this. Reopen if still an issue.
