### ISSUE TITLE
Cassandra Sink JSON parse fail with error

### ISSUE THREAD

**Issue by pawan-kmr** [datamountaineer/stream-reactor#142]
I am posting some JSON with console consumers and those get inserted successfully but if producer sends JSON to kafka topic then sink get crashed even while noop is used.

Still my console consumers shows the JSON as expected and when i do post same using console producer that also works. Is it problem with serialize and deserialize.

Any suggestion.

Logs:
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('H' (code 72)): Expected space separating root-level values
 at [Source: [B@52f6ec1c; line: 1, column: 5]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('H' (code 72)): Expected space separating root-level values
 at [Source: [B@52f6ec1c; line: 1, column: 5]

**Comment by stheppi** [comment]
What is the json? Use kafka console consumer to grab it.
Get the latest cod, build and deploy and will log the json messag e

**Comment by pawan-kmr** [comment]
i built latest code of stream reactor and used latest jar but still could not get right logs. I also have that JSON logged in producer program/logs. JSON looks correct because i posted same using console producer and that went through and inserted... simple key:value things. But what is the deserializer JsonConverter expect ?

**Comment by andrewstevenson** [comment]
What is the setup of your Connect cluster?

**Comment by andrewstevenson** [comment]
This is coming from the framework not the sink.

**Comment by pawan-kmr** [comment]
Initially I was using confluent & streaming reactor & I was facing this error. Then I moved to Apache Kafka & streamreactor jars in lib but still faced same error. can you help me to understand if producer says the key & value are byte []

			pm := &kafka.ProducerMessage{
				Topic: msg.Topic,
				Key:   kafka.ByteEncoder(msg.Key),
				Value: kafka.ByteEncoder(msg.Payload),
t.Printf("---\nTo Kafka\nTopic: %s\nKey: %x\nPayload:\n%s\n---\n\n", pm.Topic, pm.Key, pm.Value)

**Comment by stheppi** [comment]
Did you set the use.schema=false on the JsonConverter?

**Comment by pawan-kmr** [comment]
In connect-distributed.properties

key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

**Comment by stheppi** [comment]
Take your raw bytes and pass it through JsonDeserializer instance (class in kafka) and see. What enconding do you use Utf-8?

**Comment by stheppi** [comment]
You need to check what I said earlier. You are not even getting to the sink code.

**Comment by pawan-kmr** [comment]
I am my self not specifying anything any where. Producer is not in my control. I am only using reactor sink to push it to Cassandra. So my understanding says I should ask producers to use JsonSerializer with utf-8? When i push JSON from console producer it means it uses string serializer and so sink is able to process it. So should i get producer changed to use JsonSerializer or StringSerializer?

Because I am using everything default from reactor sink.

**Comment by pawan-kmr** [comment]
What should I do if my Producer is sending actually messages which are JsonSerialized?

**Comment by stheppi** [comment]
Change your converter from jsonconverter to stringconverter. The sink will try to handle string payloads containing json.

**Comment by pawan-kmr** [comment]
I really appreciate your help this working after changing to StringConverter.

**Comment by stheppi** [comment]
Cool!
