### ISSUE TITLE
HazelcastSink - write to map

### ISSUE THREAD

**Issue by stampy88** [datamountaineer/stream-reactor#143]
Hi,
We are currently using Hazelcast as an in-memory cache for our databases. We make use of Hazelcast maps to store our data and lean heavily on the ability to create indexes on these maps: http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#indexing-queries. I was curious why the sink currently only supports writing to reliable topics and wanted to get your thoughts on adding a feature to write to maps.

thanks!

**Comment by stheppi** [comment]
@stampy88 
  We do support multiple taegets. That includes: reliable topic, ring buffer, queue, set, imap,multi map and icache. All you have to do is say in kcql 'STOREAS $'. See hazelcastsinksettings.scala for the labels for each

**Comment by stampy88** [comment]
Oh really? Cool. I didn't look at the code and was only going by the docs:

http://docs.datamountaineer.com/en/latest/hazelcast.html

``` The connector takes the value from the Kafka Connect SinkRecords and inserts a new entry to a HazelCast reliable topic. The Sink only supports writing to reliable topics.```

Thanks!

**Comment by andrewstevenson** [comment]
@stampy88 Can you raise an issue on the docs repo for this? Or submit a PR for it?

**Comment by stampy88** [comment]
@andrewstevenson I'll have a PR in a bit

**Comment by stampy88** [comment]
@andrewstevenson https://github.com/datamountaineer/docs/pull/18
