### ISSUE TITLE
Suggestion - Add USE TTL to Cassandra Sink

### ISSUE THREAD

**Issue by joewood** [datamountaineer/stream-reactor#155]
Adding the TTL for the INSERT statement as a configuration would be useful, especially with multiple sink connectors writing to the same table with different TTL requirements.

Documentation about TTL: https://docs.datastax.com/en/cql/3.3/cql/cql_using/useTTL.html

**Comment by andrewstevenson** [comment]
This is possible, I just need to check its supported with the json insert functionality.

**Comment by andrewstevenson** [comment]
@joewood  Done. TTL can now be set via KCQL.
