### ISSUE TITLE
Retry Count Tracking on Sink Connector

### ISSUE THREAD

**Issue by joewood** [datamountaineer/stream-reactor#157]
I'm using the JMS Sink Connector writing to a Queue. I'm using the RETRY error policy with a max retry of 20 (defaults).

The problem is that Kafka is writing to the JMS queue much faster than the JMS queue consumer can drain it. This is fine as I would expect the connector to write, hit `queue full`, throw an exception, wait for an interval and try again. Effectively backing off the queue.

What I do see is that the error accumulation does not reset once the sink successfully writes to the queue. So after the 20th time of hitting `queue full` the connector aborts.

I see some logic in the **kafka-connector-common** that implies tracking is based on the error message. In this case, the **queue full** error is inside an inner linked exception, so may not be visible at the top level.

Ideally the JMS sink should special case back-pressure and ease off on writes without accumulating. That may be difficult as the error is not easily identifiable. Another approach could be to configure a `high-watermark` on the queue, periodically [check the size](http://stackoverflow.com/questions/13603949/count-number-of-messages-in-a-jms-queue) and back-off if the queue is near the limit.

**Comment by stheppi** [comment]
@joewood  we push the fix on error reset. you will need to take the latest either from master for 3.2 or the 3.1.2 branch for confluent 3.1.2 version.
back pressure can be driven by the kafka consumer settings. you can set max.poll.records to a lower number (default is 500). you can set it as low as 1. you can tweak the fetch size (total or per partition), have a min size returned.So Kafka has back pressure built in and having the connector with such logic wouldn't add any value.

**Comment by joewood** [comment]
Thanks for the quick turnaround.
