### ISSUE TITLE
kafka-connect-cli returns incorrect version

### ISSUE THREAD

**Issue by smifun** [datamountaineer/stream-reactor#178]
Hi
When running help for cli tool it returns incorrect version. It shows 0.7 although I'm running  kafka-connect-cli-1.0-all.jar.

```
kamil$ java -jar kafka-connect-cli-1.0-all.jar --help
kafka-connect-cli 0.7
...
```

**Comment by andrewstevenson** [comment]
This is bug on the tools repo.

https://github.com/datamountaineer/kafka-connect-tools/blob/08f96352e3c29ab2c0c5943ae9916cd52d0f99c7/src/main/scala/com/datamountaineer/connect/tools/Cli.scala#L128

**Comment by andrewstevenson** [comment]
Fixed on kafka-connect-tools repo. Updating the version in stream reactor
