### ISSUE TITLE
issue/complexities with JMSSource Connector

### ISSUE THREAD

**Issue by michaelandrepearce** [datamountaineer/stream-reactor#184]
after much trialling the new JMSSource connector, and fixes. I thought it be useful to give some end user feedback.

To make the JMSSource a straight through connect, I have found it is over complicated.

First off, for each input jms queue/topic i need to provide a source converter, it be much better to be able to provide the config option to supply a global default.

Secondly i need to provide the source jms destination in the connect.jms.queues, and then again in kcql and also for the converter.

like wise with the destination topic (note the topic, isn't required by the connector but tools ala landoop tee off this config info), seems a lot of duplication that can be simplified.

tbh it almost seems the KCQL here is currently redundant 

INSERT INTO takes a singular destination it seems, so it might as well be the default field "topic" to represent this.

SELECT doesn't select reduce any input columns i had tried SELECT bytes_payload in hope it would return just the byte array, but it had no effect, it still returned the whole schema/value in JMSStructMessage when i don't set my own converter.

FROM is default of the list of jms queues/topics.

Maybe KCQL has value for some other use case (when it's works for JMSSource), but it seems it could be made optional and if not provided, can be deduced by the other properties as INSERT INTO <topic> SELECT * FROM connect.jms.queues + connect.jms.topics.

lastly the most common default connection factory in jndi is named "ConnectionFactory" why not default this (obviously allow this to be changed) to reduce more config.

Below is what I've ended up having to configure, and below that what i think a streamlined version could look like.

current:
```
{
  "name": "JMSSourceConnector2",
  "tasks.max": "1",
  "connector.class": "com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector",
  "connect.jms.initial.context.factory": "org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory",
  "connect.jms.connection.factory": "ConnectionFactory",
  "connect.jms.url": "tcp://artemis-2.test.mydomain.local:62616",
  "connect.jms.queues": "jmsQueue",
  "connect.jms.kcql": "INSERT INTO test_kafka_connect SELECT * FROM jmsQueue"
  "connect.jms.source.converters": "jmsQueue=com.datamountaineer.streamreactor.connect.converters.source.BytesConverter",
  "topic": "test_kafka_connect",
  "value.converter": "org.mydomain.kafka.connect.ByteArrayConverter"
}
```
reduced possible config 
```
{
  "name": "JMSSourceConnector2",
  "connector.class": "com.datamountaineer.streamreactor.connect.jms.source.JMSSourceConnector",
  "connect.jms.initial.context.factory": 
"org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory",
  "connect.jms.url": "tcp://artemis-2.test.mydomain.local:62616",
  "connect.jms.queues": "jmsQueue",
  "connect.jms.source.default.converter": "com.datamountaineer.streamreactor.connect.converters.source.BytesConverter",
  "topic": "test_kafka_connect",
  "value.converter": "org.mydomain.kafka.connect.ByteArrayConverter"
}
```

maybe I'm miss understand what the KCQL will give me, or just its not doing what it should atm.

**Comment by michaelandrepearce** [comment]
Fyi, I'm happy to contribute some changes to do this, but obviously thought it first to give some feedback, as you maybe taking this tool in another direction, or i have just completely missed something.

**Comment by andrewstevenson** [comment]
Hi Michael,

Thanks for the feedback!


1.       A default global converter makes senses but also keeping the option to override per topic/queue.

2.       Having to describe the source destination twice is not optimal, my approach would be to try and take this from KCQL, the Connector handles multiple statements so when you want to start sourcing multiple JMS destination it can help reduce the complexity.

3.       KCQL generally makes more sense for sinks however we could use it to cherry pick fields from the JMS Source sink as we have a schema. This isn’t implemented at the moment.

4.       Agree with defaulting the ConnectionFactory

I would like to have as much of this functionality exposed via KCQL as possible. @Stefan Bocutiu<mailto:stefan@datamountaineer.com> Thoughts?

Please feel free to submit PRs.

Regards,

Andrew

**Comment by stheppi** [comment]
I would keep kcql there. And add support for specifying the converter in there. If is not defined then we fallback on the default.

**Comment by michaelandrepearce** [comment]
I have raised 
https://github.com/datamountaineer/stream-reactor/pull/185/files

which adds/address's points 1 + 4 (plus also provides a connect converter to support optional byte array that is passed, to support straight through byte[] copying)

**Comment by stheppi** [comment]
@michaelandrepearce i will cover the KCQL. Hopefully at some point next week the support for it will be there and we can close this

**Comment by michaelandrepearce** [comment]
@stheppi did you make any strides on this?

**Comment by stheppi** [comment]
@michaelandrepearce 
i have upgraded the code to kcql 1.0.4 which adds support for setting the converter in kcql. i will find some time over the next fewdays to update the JMS source/sink to use it

**Comment by andrewstevenson** [comment]
@michaelandrepearce I've upgraded the connectors to get the converters (withconverter)  and destinationtype (withtype) for topics/queues from kcql.

`insert into kafka_topic select * from jms_topic withconverters=myconverter withtype topic`
