### ISSUE TITLE
Elasticsearch 5 - use HTTP

### ISSUE THREAD

**Issue by sander-su** [datamountaineer/stream-reactor#213]
With elasticsearch 5 it is the advised way it to connect via http, not the internal transport protocol. 
The new elastic 5 connector uses the internal transport protocol protocol. 
Can it be adjusted to http protocol? It is supported by the used client. 
This way future elastic protocol changes do not need a new connector and one connector can be used for es 2 and 5.
Our elasticsearch setup only accepts clients via http and we like KCQL so this poses a problem

**Comment by stheppi** [comment]
@sander-su,
   thanks​ for looking at our connector. Your request for Http support is valid, however making it the only option is too restrictive. We already have users (i.e British Gas) which will most likely never consider dropping TCP in favour of HTTP. 

There are two approaches for this. We welcome pull requests to add the functionality or we can offer paid support in which case we can prioritise the work. You can contact @andrewstevenson (andrew@datamountaineer.com)  to discuss the details

**Comment by sander-su** [comment]
@stheppi thank for the quick response.
We´ll see what is the best option for us.

**Comment by andrewstevenson** [comment]
It will more than likely get added at some point, but it’s not a priority now unless it’s on a commercial basis. I notice you guys are in NL, are you going to the Kafka meetup tonight?

**Comment by sander-su** [comment]
@andrewstevenson 
Was there a previous time and heard your talk @ eneco but had to leave a bit earlier that time, sorry.
For tonight doesn't fit my nor collegues schedule. So hopefully other time.

As we are bit offtopic; how do I get the timestamp in kcql? or is that an issue for the kcql repo?
