### ISSUE TITLE
Typo in mongodb-sink.properties file leads to BadRequest exception

### ISSUE THREAD

**Issue by leschekhomann** [datamountaineer/stream-reactor#214]
In the mongodb-sink.properties file the KCQL configuration parameter is connect.mongo.sink.**kqcl** instead of connect.mongo.sink.**kcql**. This leads to a BadRequest exception.

**Comment by andrewstevenson** [comment]
@leschekhomann can you open a PR?

**Comment by leschekhomann** [comment]
@andrewstevenson Done.
