### ISSUE TITLE
Recovering kafka message to influxdb from certain date / offset

### ISSUE THREAD

**Issue by nirvanesque** [datamountaineer/stream-reactor#216]
Hello,

In the connector for influxDB or druid, is it possible to set in a corresponding properties file a date or offset from when/ where to fetch messages (and not from beginning) ? 

Thanks in advanced for your reply

**Comment by stheppi** [comment]
@nirvanesque
  The connector code can't instruct the connect framework to consume from offset x. This is operational. You need to 1.stop your connector;
2. Identify your offset for the topics and partition
3. Using your sink name (is used as group id) you have to set the offset for all the topics and partitions to the values you want.
4. Start the influxdb sink
