### ISSUE TITLE
INFO meta store storage HASN'T /some/path (com.datamountaineer.streamreactor.connect.ftp.ConnectFileMetaDataStore:49)

### ISSUE THREAD

**Issue by abdbaddude** [datamountaineer/stream-reactor#219]
I am using CP3.2.1 and working with the kafka-connector-ftp to tail files on a remote server. I connect successfully , however  I get a lot of the following on read by the kafka-connector
`INFO meta store storage HASN'T /tmp/1 (com.datamountaineer.streamreactor.connect.ftp.ConnectFileMetaDataStore:49)`

I can't see the contents of the files in the topic and after a while , I get OOM errors. Where can I configure the meta store storage ? How do I solve this problem. I start my kaka-connector in distributed mode.

**Comment by andrewstevenson** [comment]
We aren't actively supporting this connect yet and it's not upto date with the original at Eneco, https://github.com/Eneco/kafka-connect-ftp please check with them

**Comment by abdbaddude** [comment]
Thanks

**Comment by andrewstevenson** [comment]
we plan to bring it in and overhaul it soon

**Comment by abdbaddude** [comment]
ok
