### ISSUE TITLE
Bloomberg Service URI

### ISSUE THREAD

**Issue by pliew** [datamountaineer/stream-reactor#220]
I notice that currently the service uri's that are supported are //blp/refdata and //blp/mkdata.

I keep going over the blpapi docs and everywhere, the service URI is //blp/mktdata.  Is this a misunderstanding on my part?

Great work and thanks!

**Comment by andrewstevenson** [comment]
@pliew looks like a typo...are you able to test this? We no longer have access to a connection?

**Comment by pliew** [comment]
Hi @andrewstevenson 

I recompiled the connector correcting the typo, but it looks like it's not operating correctly.

Two issues come up:
1.  For refdata, it seems to only insert a static amount of data (not sure if this is just performing a snapshot of somesort)
2.  The connector doesn't seem to store the entire element.

I haven't been able to dive deeper into this but at first glance that is what I could spot out.

**Comment by andrewstevenson** [comment]
@pliew We can have a look but since we don't have any connection to bloomberg anymore it's difficult to check, we can start looking at the issues but any help from your side is much appreciated. Do you have any logs of what your are seeing?

**Comment by Antwnis** [comment]
Hi @pliew 

Could you please join the Slack channel - so that we can have a direct chat and try to resolve your issues ?

There's a button at https://datamountaineer.com/contact/

**Comment by andrewstevenson** [comment]
fixed in master.
