### ISSUE TITLE
Support of Multiple KCQL Sentences in cassandra.sink.kcql

### ISSUE THREAD

**Issue by cgiraldo** [datamountaineer/stream-reactor#222]
I need to store a kafka message in multiple cassandra tables.
I set the connect.cassandra.sink.kcql to a string with two statements separated by ";", but the last statement is only executed.
example of connect.cassandra.sink.kcql=INSERT INTO flow_by_src SELECT id, eventtime, src_ip, dst_ip FROM flow; INSERT INTO flow_by_dst SELECT id, eventtime, src_ip, dst_ip FROM flow

**Comment by andrewstevenson** [comment]
@cgiraldo We are working on a new release, we'll see if we can get this in.

**Comment by stheppi** [comment]
this is now in master. you can either wait for our next release or get and build the code yourself.
