### ISSUE TITLE
MQTT connector - Support subscription to wildcard MQTT topics

### ISSUE THREAD

**Issue by dls314** [datamountaineer/stream-reactor#228]
I'm interested to know if the MQTT connector can subscribe to wildcard containing topics.

I don't see anything to prevent it, provided that all topics covered by the wildcard can use the same converter.

**Comment by andrewstevenson** [comment]
@dls314 We rely on KCQL for the mapping, it's possible but we have to default to the MQTT topic name and default converters.

**Comment by andrewstevenson** [comment]
@dls314 We have upgraded to KCQL2 on master, a release is pending. It will support wildcard subscriptions in the `connect.mqtt.kcql` configuration. It hasn't been tested yet, a PR for a unit test would be awesome. You can take the latest commits on master and try it out.

**Comment by andrewstevenson** [comment]
@dls314 Test and available on Master and next release, only for Kafka 0.11 and Confluent 3.3

**Comment by brokenjacobs** [comment]
How do you specify avro schemas when you wildcard the mqtt subscription?
