### ISSUE TITLE
Improvement on Cassandra source

### ISSUE THREAD

**Issue by Antwnis** [datamountaineer/stream-reactor#23]
The value of the parameter `connect.cassandra.authentication.mode` can easily be inferred. So remove this configuration parameter and infer in code  like

    if ( ( connect.cassandra.username.length >= 0 ) && ( connect.cassandra.password >= 0 ) ) {
      // use authentication
    }  

I also suggest to rename `connect.cassandra.contact.points` -> `connect.cassandra.hosts` with description `The cassandra hosts to connect to` 

Also you mention `connect.kudu.sink.error.policy`
at 
http://docs.datamountaineer.com/en/latest/cassandra.html#source-connector-configuration-incremental 
I guess that is a type

**Comment by andrewstevenson** [comment]
Done.
