### ISSUE TITLE
Warn on MongoDB sink if collection name contains invalid chars

### ISSUE THREAD

**Issue by Antwnis** [datamountaineer/stream-reactor#233]
```connect.mongo.sink.kcql=INSERT INTO smoketest-collection SELECT * FROM smoketest-topic```

The above query seems OK - but mongo is not happy with collections containing the `-` character. The connector could give a big WARNING (or even ERROR) in case invalid chars are used in collection name

**Comment by andrewstevenson** [comment]
@Antwnis I'll look at this now as I'm tackling SSL on mongo.
