### ISSUE TITLE
CoAP connector - support PSK

### ISSUE THREAD

**Issue by amq** [datamountaineer/stream-reactor#243]
In very constrained environments like NB-IoT where monthly data limits will be around 1MB it would be beneficial to use PSK instead of certificates.

**Comment by andrewstevenson** [comment]
@amq we can look at this. We are busy preparing a new release. I'm not sure it will make in but PRs are always welcome!

**Comment by andrewstevenson** [comment]
@amq I've had a look at this but for the Californium libs you need to set the identify with public and private keys anyway? Maybe you have more insight here? I can add public/private key support.
