### ISSUE TITLE
i'm cannot put timestamp to sink cassandra

### ISSUE THREAD

**Issue by deztonz** [datamountaineer/stream-reactor#247]
i'm cannot put timestamp to sink cassandra

avro format
{
  "value_schema": "{\"type\":\"record\",\"name\":\"myrecord\",\"fields\":[{\"name\":\"assetfileid\",\"type\":\"string\"},{\"name\":\"assetfilename\",\"type\":\"string\"},{\"name\":\"assetfiletype\",\"type\":\"string\"},{\"name\":\"createdate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}},{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"filesize\",\"type\":\"int\"},{\"name\":\"fileurl\",\"type\":\"string\"},{\"name\":\"updatedate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]}",
  "records": [
    {
      "value": {
        "assetfileid": "af1edf50-7c0b-11e7-94ee-50a8daa321951",
        "assetfilename": "test_name_31",
        "assetfiletype": "post_image",
        "createdate": null,
        "filename":"1_1502177524088.png",
        "filesize": 537287,
        "fileurl": "http://cdn.ithub.space/bob/1_1502177524088.png",
        "updatedate": null
      }
    }
    
  ]
}

cassandra table
CREATE TABLE bub_db.assetfile (
	assetfileid uuid,
	assetfilename text,
	assetfiletype text,
	createdate timestamp,
	filename text,
	filesize bigint,
	fileurl text,
	updatedate timestamp,
	PRIMARY KEY (assetfileid)
)

**Comment by andrewstevenson** [comment]
@deztonz your updatedate is null. We use cassandras json insert functionality.

**Comment by andrewstevenson** [comment]
So you insert null
