### ISSUE TITLE
ElasticSearch authentication

### ISSUE THREAD

**Issue by Antwnis** [datamountaineer/stream-reactor#25]
Add authentication mechanisms. Two ideas:

How to connect using a username/token to elastic-search ?

Another mechanism when securing an Elastic-Search server is putting a `nginx` proxy in front of it.
The proxy blocks connection requests unless a special header is set - and a particular token 

i.e. on the HTTP request if 

```
'HEADER_MY_SECRET_ELASTIC_TOKEN' : 'MY_SECRET_PASSWORD'
```

Then `nginx` allows proxying the request

**Comment by andrewstevenson** [comment]
Does elastic4s do this?

**Comment by Antwnis** [comment]
Closing - and will re-open if requested & supported
