### ISSUE TITLE
Elastic5 connector bulk size feature

### ISSUE THREAD

**Issue by panda87** [datamountaineer/stream-reactor#264]
Can you pls add bulk_size configuration to es5 connector in order to handle the bulks sizes we send to es? This is one of the best ways for gaining performance during indexing time.

Thanks
D.

**Comment by stheppi** [comment]
Hey,
 `connect.elastic.batch.size` configuration entries does that.
 We will ad the details to the documentation.

**Comment by panda87** [comment]
Ohhh thanks, I tried to find this in the docs. Thanks a lot!

**Comment by Antwnis** [comment]
@panda87 feel free to report what works best for your use case regarding batch sizes / message sizes. It will be good for the community to have a reference, and it can be added to the docs as well

**Comment by panda87** [comment]
It usually depends on the docs sizes for the specific index.
It's very common for my use case to use above batch of 5,000 but for other indices even more.
Logstash from version 5.x started to send every 20mb(!) while ES recommends more than 10mb (of course depends on cpu, mem and disks).

In filebeat conf im using the numbers above but also set `flush_interval` as well as `bulk_max_size` to make sure im not waiting for 5K logs for example for getting any of logs.

btw, @Antwnis is this plugin has `flush_interval` arg?
