### ISSUE TITLE
Cassandra Sink support for DELETE functionality

### ISSUE THREAD

**Issue by sandonjacobs** [datamountaineer/stream-reactor#270]
The use case for this would be when the source topic is a compacted topic, perhaps capturing data changes from an upstream source. 

Let's say a record is deleted from the upstream source and that delete operation is propagated to the kafka topic, with the key of the kafka message as the PK of the record in the targeted cassandra table - meaning the value of the kafka message is now `null`.

Ideally, the sink connector could grab the key and see that the value is `null` then issue a DELETE from the table using the key value(s).

**Comment by sandonjacobs** [comment]
Another way to think of the compacted topic is as a copy of the current state of the upstream data store (i.e. a database table somewhere). Perhaps my cassandra table is my application's view of what it cares about in that upstream table, and it can be ingested in full at application startup or anytime to refresh it's view of the world, without attaching to the source datastore. 

See Kleppmann's ["Turning the Database Inside-Out."](https://www.youtube.com/watch?v=fU9hR3kiOK0)

**Comment by Antwnis** [comment]
Hey @sandonjacobs we understand fully the requirement - especially in the world of CDC

One point from my side, is that this functionality will need to be built-in, in every single connector (Elastic, Cassandra, etc) and that it should be optional/configurable

Would you like starting that work on the Cassandra Sink ? We'll be happy to accept a PR - and we can then make sure, that functionality is consistent across the entire stream-reactor distribution of connectors

**Comment by sandonjacobs** [comment]
I am looking at the Cassandra Sink as we speak. Trying to make sure I have the configuration bases covered first, with optional params and defaults. Then I will try to incorporate them.

**Comment by andrewstevenson** [comment]
@sandonjacobs Thanks, I'll update the docs. Nice job!

**Comment by sandonjacobs** [comment]
Based on code-review comments, there were still some things I wanted to add. I will submit those as enhancements in future pull requests.
