### ISSUE TITLE
WARN cannot connect to ftp: java.lang.Exception: cannot login to ftp: 530: null

### ISSUE THREAD

**Issue by msiddiqi** [datamountaineer/stream-reactor#273]
I am using version: 0.2.6. The connector starts and initializes successfully but then it starts throwing these messages on the log. Can you please help? Just to note that I can login to the ftp site using chrome with the same credentials.

[2017-09-10 02:59:54,585] WARN cannot connect to ftp: java.lang.Exception: cannot login to ftp: 530: null (com.datamountaineer.streamreactor.connect.ftp.FtpMonitor:251)
[2017-09-10 02:59:54,586] WARN ftp monitor failed: java.lang.Exception: cannot login to ftp: 530: null (com.datamountaineer.streamreactor.connect.ftp.FtpSourcePoller:114)
[2017-09-10 02:59:54,586] INFO let's backoff PT2M (com.datamountaineer.streamreactor.connect.ftp.FtpSourcePoller:116)
[2017-09-10 03:01:55,176] INFO poll (com.datamountaineer.streamreactor.connect.ftp.FtpSourcePoller:103)

**Comment by andrewstevenson** [comment]
@msiddiqi Whats your configuration?

**Comment by msiddiqi** [comment]
Here is my config:
name=ftp-source
#connector.class=com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceConnector
connector.class=com.datamountaineer.streamreactor.connect.ftp.FtpSourceConnector
tasks.max=1
 
#server settings
connect.ftp.address=FTP_ADDRESS
connect.ftp.user=USER_NAME
connect.ftp.password=PASSWORD

#refresh rate, every minute
connect.ftp.refresh=PT1M
#ftp.refresh=PT1M

#ignore files older than 14 days.
connect.ftp.file.maxage=P14D
#ftp.file.maxage=P14D

#monitor /forecasts/weather/ and /logs/ for appends to files.
#any updates go to the topics `weather` and `error-logs` respectively.
#connect.ftp.monitor.tail=/ETFUser/:ftp-files,/logs/:error-logs
 
#keep an eye on /statuses/, files are retrieved as a whole and sent to topic `status`
connect.ftp.monitor.update=/data/:ftp-files-data
#ftp.monitor.update=/data/US_HEDI/Valuation/:ftp-files-data
#topic=tpc
 
#keystyle controls the format of the key and can be string or struct.
#string only provides the file name
#struct provides a structure with the filename and offset
connect.ftp.keystyle=struct
#ftp.keystyle=struct

**Comment by andrewstevenson** [comment]
@msiddiqi remove the `connect` prefix on the options, or build the latest jar from master, we had a regression when merging in Eneco's latest fixes. The prefix was accidently dropped. Release 3.0.0 has this, we have fixed on master.

**Comment by msiddiqi** [comment]
I did try that. It was working fine with the latest version but it throws error with this version. But the latest version has other regression issue, which makes it not usable.

**Comment by andrewstevenson** [comment]
Build from master.

**Comment by andrewstevenson** [comment]
The 0.3.0 release will ignore the options being with connect which is probably why you can't connect.

**Comment by msiddiqi** [comment]
So when I remove the connect prefix, I get the following error:
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 6 error(s):
Missing required configuration "connect.ftp.address" which has no default value.
Missing required configuration "connect.ftp.user" which has no default value.
Missing required configuration "connect.ftp.password" which has no default value.
Missing required configuration "connect.ftp.refresh" which has no default value.
Missing required configuration "connect.ftp.file.maxage" which has no default value.
Missing required configuration "connect.ftp.keystyle" which has no default value.
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:97)

**Comment by andrewstevenson** [comment]
Can you clarify which version of the stream reactor you are using?

**Comment by andrewstevenson** [comment]
@msiddiqi Did you resolve your issue?

**Comment by andrewstevenson** [comment]
@msiddiqi I'm closing this issue as all our tests can connect.
