### ISSUE TITLE
Need to get measurement name from topic in influxdb

### ISSUE THREAD

**Issue by kbrems** [datamountaineer/stream-reactor#287]
We are using the stream reactors connectors 0.3.0 in the latest landoop/fast-data-dev docker container. For our use case, the measurement name for influxdb comes in the topic data, not a name we can hard code in the connector KCQL. For example, input topic data looks like this:

{"time":"1506111298264000001","_UUID":"12345","name":"cpu_utilization","value":40}
{"time":"1506111298264000002","_UUID":"6789","name":"storage","value":30}

For example, I want to insert the time, _UUID and value into a measurement in influxdb called "cpu_utilization" or "storage".  The KCQL seems to require the measurement name to be hard coded in the configuration. ie:

"connect.influx.kcql": "INSERT INTO DeviceMetrics SELECT * FROM metric_topic",

Which will insert into a DeviceMetrics table. But what I need to do is something like this:

"connect.influx.kcql": "SELECT name from metric_topic as measurement; INSERT INTO measurement SELECT time, _UUID, value from metric_topic,

Is there any way to do this using KCQL?

**Comment by andrewstevenson** [comment]
@kbrems So you want to use a field value from the payload as the target measurement?

**Comment by andrewstevenson** [comment]
@kbrems kql supports tag which are preferred over putting data in the measurement 

https://docs.influxdata.com/influxdb/v1.3/concepts/schema_and_data_layout/

**Comment by andrewstevenson** [comment]
@kbrems see the tagging docs http://docs.datamountaineer.com/en/latest/influx.html

**Comment by andrewstevenson** [comment]
@kbrems Using a field value as measurement name isn't supported but can be added PRs  welcome!

**Comment by Antwnis** [comment]
On the REDIS sink connector, we've built exactly what you are asking. In terms of KCQL you define 

`PK myField`

Then the value of the myField is extracted and becomes the name of the Key

**Comment by stheppi** [comment]
@kbrems 
  We added support for your .requirement You can take the latest code from master and build it locally until we make a release.

  Now you can source the measure name from the payload:

```INSERT INTO dummyMeasure SELECT ... FROM topicA WITHTARGET fieldA```  
If the value for fieldA is null (it doesn't exist it will endup using `dummyMeasure`).

Of course you can specify nested fields.

**Comment by ThinkontrolSY** [comment]
@kbrems 
Do you finish your project?
I have tried this kcql, and it works for me, I think it should meets your requirement
```sql
INSERT INTO name SELECT * FROM metric_topic WITHTARGET = name
```

**Comment by kbrems** [comment]
Our project has since moved away from using Kafka, so our kcql requirement went away. Still seems like a useful feature though!

**Comment by andrewstevenson** [comment]
@kbrems Out if curiosity what did you move to?

**Comment by kbrems** [comment]
We are now using gRPC
