### ISSUE TITLE
kafka-connect-influxdb - Add configuration to specify Point measurement time precision

### ISSUE THREAD

**Issue by jmwilli25** [datamountaineer/stream-reactor#295]
The default point precision of InfluxDB is nanosecond though it is configurable. https://github.com/datamountaineer/stream-reactor/blob/aff89ec5338084c82df2bd860b942452d412599b/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala#L124
https://github.com/datamountaineer/stream-reactor/blob/aff89ec5338084c82df2bd860b942452d412599b/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala#L165
https://github.com/datamountaineer/stream-reactor/blob/aff89ec5338084c82df2bd860b942452d412599b/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/InfluxBatchPointsBuilder.scala#L204
all force point precision to milliseconds. I propose leaving that as default, no breaking changes, and add a configuration for the allowable Enums of [`java.util.concurrent.TimeUnit`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html) as allowed by [`org.influxdb.dto.Point`](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/dto/Point.java#L189)

To limit the scope, the initial implementation should only acknowledge the new configuration value if the time is specified as a long so [`TimestampValueCoerce.scala`](https://github.com/datamountaineer/stream-reactor/blob/master/kafka-connect-influxdb/src/main/scala/com/datamountaineer/streamreactor/connect/influx/writers/TimestampValueCoerce.scala) doesn't need a complete rewrite to handle all the different precision levels.

**Comment by stheppi** [comment]
@jmwilli25 
 You can download the latest and now the code allows in KCQL to do ```  SELECT ...FROM ..  TIMESTAMP fieldA TIMESTAMPUNIT NANOSECONDS/MILLISECONDS/... ``` any of the java.util.concurrent.TimeUnit values
