### ISSUE TITLE
Add VERSION and VERSION_DOC to all connectors

### ISSUE THREAD

**Issue by Antwnis** [datamountaineer/stream-reactor#297]
As Kafka Connect does not allow the exposure of the CONNECTOR version we can add the additional information as per a configuration key/default value/doc

i.e. on every Connector we should add 

    CONNECTOR_VERSION = s"$PREFIX.connect.version"
    CONNECTOR_VERSION_DEFAULT = "0.3.0"
    CONNECTOR_VERSION_DOC = "http://docs.datamountaineer.com/en/0.3.0/influx.html"

At release time the CI process (@andmarios) will `sed` this config and append to the version the commit-id resulting into 

    CONNECTOR_VERSION_DEFAULT = "0.3.0 aff89ec"

**Comment by andrewstevenson** [comment]
Adding the following to the Manifest, In the common project we can add the manifest reader.


 {
            attributes( "Implementation-Title": "Stream Reactor",
                        "Implementation-Version": project.version,
                        "Created-By" : "DataMountaineer",
                        "Created-At" : getDateTime(),
                        "Git-Commit-Hash": getGitHash(),
                        "Git-Tag": getGitTag(),
                        "Documentation" : "http://docs.datamountaineer.com/en/${project.version}/"
            )
        }

**Comment by Antwnis** [comment]
We also want a UI to be able to query i.e. via /validate end-point in order to return the version of stream-reactor
