### ISSUE TITLE
Publish to maven

### ISSUE THREAD

**Issue by andrewstevenson** [datamountaineer/stream-reactor#5]

**Comment by Antwnis** [comment]
I think we can now close this one

**Comment by joewood** [comment]
Was it decided not to publish to maven?

**Comment by andrewstevenson** [comment]
No decision yet we just need to find the time!

Any reason the github release page isn't sufficient?  Are you mirroring to an internal repo?
________________________________

**Comment by joewood** [comment]
Yes, it's just a bit easier to pull down using Ansible via Maven than download and unpack. Not a huge deal as we can publish to our own local Artifactory. I just saw this as closed and thought it was done, but couldn't find it.

**Comment by andrewstevenson** [comment]
We can reopen at look at it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joewood** [comment]
Any update on this? Would really like to see the full set of components in Maven if possible.

**Comment by andrewstevenson** [comment]
@joewood  We are planning a release soon, we hope to get it in for that.

**Comment by joewood** [comment]
I see some updates in Maven - is this now complete for v.3?

**Comment by andrewstevenson** [comment]
@joewood There's updates for some of dependencies, I'll look at publishing to maven next week.

**Comment by joewood** [comment]
Hi @andrewstevenson just checking in to see if there's been any progress on the publication?

**Comment by andrewstevenson** [comment]
@joewood yeah sorry. we are busy getting Lenses for initial release. I'll have a look tomorrow.

**Comment by andrewstevenson** [comment]
@joewood Which version are you using?

**Comment by joewood** [comment]
Version 0.2.6, but I can upgrade to 0.3.0 if you publish that version.

**Comment by andrewstevenson** [comment]
@joewood I've published 0.3.0, it'll take a bit to propagate out

**Comment by joewood** [comment]
Thanks @andrewstevenson !!

**Comment by Antwnis** [comment]
Hi @joewood we also have a Bloomberg source connector, that we'd like to certify with Bloomberg. Do you think you could make us some introductions :-) ?

**Comment by joewood** [comment]
Thanks for the publish. There seems to be a problem with some of the dependencies though, running the following command results in 2 missing dependencies:

```bash
mvn dependency:get -Dartifact=com.datamountaineer:stream-reactor:LATEST  -Ddest=.
```

```
[WARNING] Missing POM for io.confluent:kafka-connect-avro-converter:jar:3.3.0
[WARNING] Missing POM for io.confluent:kafka-schema-registry:jar:3.3.0
```

**Comment by andrewstevenson** [comment]
@joewood I'll check,  I do know they are marked as provide in our build.gradle

**Comment by joewood** [comment]
I think it's supposed to resolve to the confluent repo `http://packages.confluent.io/maven/`. The artifacts appear to be in that repo - e.g.: http://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/3.3.0/kafka-connect-avro-converter-3.3.0.jar

**Comment by joewood** [comment]
OK, it seemed to be a Artifactory remote repo issue my side. It resolves correctly when going directly to the confluent repo. All good.
