### ISSUE TITLE
Add capability for RethinkDB Connect sink to work with schemaless Kakfa topic

### ISSUE THREAD

**Issue by timchan-lumoslabs** [datamountaineer/stream-reactor#62]
We currently have heterogenous game meta data in JSON appearing on one topic in Kafka.
We would like to utilize a RethinkDB Connect sink so that it will just dump this data into a single RethinkDB table. We can not apply a schema on this data at the moment.

**Comment by dollschasingmen** [comment]
i got u tim

**Comment by stheppi** [comment]
We have committed the latest changes supporting schemaless records as well as records with schema set to STRING and payload to be a json string. This meets all the functionality of  KCQL (picking fields, renaming fields, ignoring fields)
