### ISSUE TITLE
blockchain connector has an extra e in datamountaineer

### ISSUE THREAD

**Issue by andmarios** [datamountaineer/stream-reactor#63]
The blockchain connector's path is
```
kafka-connect-blockchain/src/main/scala/com/datamountaineeer/streamreactor/connect/blockchain
```
Notice the extra `e` in `datamountaineer`. :)
It changes the connector's class name and is a bit difficult to catch for the user.

**Comment by andrewstevenson** [comment]
Fixed in cp-3.0.1 branch
