### ISSUE TITLE
gradle fatJar results in blockchain failure

### ISSUE THREAD

**Issue by anuragphadke** [datamountaineer/stream-reactor#69]
Platform: OS X
git clone https://github.com/datamountaineer/stream-reactor.git
gradle fatJar

:kafka-connect-blockchain:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kafka-connect-blockchain:test'.
> org/gradle/api/logging/configuration/ConsoleOutput

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by andrewstevenson** [comment]
You need to use gradle 3
