### ISSUE TITLE
Enhance Redis KCQL for time-series ( Using Redis Sorted Sets)

### ISSUE THREAD

**Issue by Antwnis** [datamountaineer/stream-reactor#83]
# Redis & Timeseries 

Redis is used for timeseries use-cases like: 
 • Sell price and volume of a traded stock
 • Data gathered from sensors embedded inside IoT devices

1) A common technique is to use a redis `Sorted Set` and create a set i.e. called <USD2GBP> and 
store i) the timestamp in millis as the `score` and ii) encode both the actual value/s & the
timestamp as the `value`, in a *flat* or *Json structure*

flat-example:
```rediscli
ZADD USD2GBP 1392141527245 1392141527245:0.7983
ZADD USD2GBP 1392141529245 1392141529245:0.7982
ZRANGE USD2GBP 0 -1
```

json-example:
```rediscli
ZADD EUR2GBP 1392141527298 '{"timestamp":1392141527245,"price":0.8562}'
ZADD EUR2GBP 1392141529299 '{"timestamp":1392141529245,"price":0.8603}'
ZRANGE EUR2GBP 0 -1
```

http://www.slideshare.net/cacois/cois-palkostrata2013/29
http://www.slideshare.net/cacois/cois-palkostrata2013/33

This encoding allows read queries for historical data like: 

```
zrangebyscore USD2GBP <currentTimeInMillis - 86400000> <currentTimeInMillis>
```

To enable this capability as KCQL we will re-use STORED AS

**Comment by andrewstevenson** [comment]
So I'm thinking of using KCQL to identify a key in the payload or take the key value as the `Sorted Set` key. It should be an easy enough change.

**Comment by Antwnis** [comment]
Yes - use KCQL to define the key value as the `Sorted Set` name (like table name) 

Then we would need to define which values are tracked into the particular Sorted Set

My suggestion would be to go for a JSon representation 

An example from top of my mind:

KCQL: ```SS_TIMESERIES fieldName1 WITH fieldName2 as temp, fieldName3 as humidity``` 

This would create a SortedSet for every value of fieldName1
and store inside it records 

{ "score" : "timestamp",
  "value" : "json_encoded_temp_and_humidity" }

where the encoded payload would be

{ "timestamp" : "timestamp",
  "temp" : "tempValue",
  "humidity" : "humidityValue"
}

**Comment by andrewstevenson** [comment]
why not `insert into sorted-set-name select col1, col2 from topic pk col1` where `pk col1` says use the value in col1 from the topic as the key.

**Comment by andrewstevenson** [comment]
this means no change to kcql.

**Comment by Antwnis** [comment]
Excellent - i love your suggestion. As long as it can accommodate topics like
http://kafka-topics-ui.landoop.com/#/topic/n/yahoo-fx/ 

that carry USDGBP ++ EURGBP ++ GBP2USD time-series them .. and create one SortedSet per each time-series ..

**Comment by andrewstevenson** [comment]
it this is identifiable as a field in the payload then yes.

**Comment by andrewstevenson** [comment]
The value for the sorted set has to be a double or map[string, double] from what I see on the jedis api. So we can't just take the json payload as we do now.

**Comment by Antwnis** [comment]
Sorted Set is a Map[ score -> value ]

`score` should be `timestamp` to gain efficiencies 
`value` is de-duped ( so cannot store temperature into it) 

So we need to 
i) Have the `value` being unique even if temperature is 20,20,19,20.. etc
ii) Encode multiple metrics inside the `value` (i.e. timestamp+temp+humidity)

**Comment by stheppi** [comment]
Using a simple INSERT INTO A ... i don't see being expressive enough. The code needs to work out it is a sorted set and therefore call zadd. So i see Antwnis suggestion:
`SS_TIMESERIES fieldName1 WITH fieldName2 as temp, fieldName3 as humidity` a better approach. But if we support sorted set why not the other Redis specific types. In this case i ```
see 
`TARGET_TYPE SS/HASH/LIST`. 
@Antwnis: your point i) i don't see it being achieved unless you add the timestamp and that is guaranteed uniqueness.

**Comment by andrewstevenson** [comment]
Don't we just need to identify the score field? We can reuse the pk from kcql. It'll require a small code change. We then set the value as the json payload. The pk field must be a time stamp.

**Comment by stheppi** [comment]
how do you work out if it's a set or not? Ultimately this will translate to a different API call. In this case your suggestion can't differentiate between setting a key or adding an item to a sorted set.
Alternatively we have a specific redis sink for SS. In that case your suggestion is more than enough.

**Comment by andrewstevenson** [comment]
Or some form of type syantax on kcql. We already have withfornat and stored as.

**Comment by stheppi** [comment]
ah yes. storedas might be indeed the easy gain. then agreed. minimum impact

**Comment by andrewstevenson** [comment]
@antwnis can this be closed now?

**Comment by Antwnis** [comment]
Merged into master
