### ISSUE TITLE
Add PK support to Elastic Search connector to define the field to be used as _id 

### ISSUE THREAD

**Issue by wakurth** [datamountaineer/stream-reactor#91]
Like the connector created by confluent, it would be cool to be able to add a "key.ignore=false"-like setting, where the key in a keyed message is used as the _id in elastic search.

**Comment by andrewstevenson** [comment]
@wakurth We can probably accomplish this via KCQL something like "insert into index select * from topic PK key_col" and take the value from the key of the message.

**Comment by andrewstevenson** [comment]
@Antwnis We probably need key/value selection support on KCQL since we may want to allow users to select from either the key or payload.

**Comment by andrewstevenson** [comment]
https://github.com/datamountaineer/kafka-connect-query-language/issues/11

**Comment by Antwnis** [comment]
Fixed as per the PR just merged
