### ISSUE TITLE
Ability to configure schema name

### ISSUE THREAD

**Issue by boyenn** [datamountaineer/stream-reactor#95]
Similar to :

https://github.com/confluentinc/kafka-connect-jdbc/issues/90

The generated avro schemas by the kafka connect cassandra source default to io.confluent.avro.ConnectDefault because their schema name is null.

This causes the avro plugin to only generate this unique class.

A workaround would also be appreciated , as I cannot use serde's now.

**Comment by andrewstevenson** [comment]
@boyenn Is the table name of the target table in Cassandra enough or do you also want to replace this?

**Comment by boyenn** [comment]
That should suffice, potentially with a prefix to ensure unique names

**Comment by andrewstevenson** [comment]
We could take the key space for this?

**Comment by boyenn** [comment]
Yeah that actually sounds like it should more than suffice without making it more complicated

**Comment by andrewstevenson** [comment]
ok, we are preparing a new release in the next few days, once MQTT is merged in. I'll get it in for that.

**Comment by boyenn** [comment]
Sounds great, our project is currently blocked by this feature

**Comment by andrewstevenson** [comment]
Then I'll fix it now. We are planning on a building a Cassandra CDC source where we will publish mutations in Cassandra on to Kafka. Would that be of interest to you?

**Comment by boyenn** [comment]
It definitely sounds very interesting,
 but we don't have a use case for it in our current project.

Not to say it's a feature I wouldn't love to see! Anything that connects Kafka and cassandra more and more is greatw

**Comment by andrewstevenson** [comment]
Can you try now? I've just pushed on master.

**Comment by boyenn** [comment]
I'll quickly try it out in a VM, since I'm not currently at work (European timezone) and we don't have outside access to our test environment

**Comment by andrewstevenson** [comment]
@boyenn did it work for you?

**Comment by boyenn** [comment]
Didn't have the chance to try unfortunately

**Comment by andrewstevenson** [comment]
@boyenn I'm going to close this unless you have any objection?

**Comment by boyenn** [comment]
That's alright, we've been working on another project in the meantime so we couldn't try it out sorry.
